<a href="https://colab.research.google.com/github/diadkinang/DS-study/blob/main/HW3_Diadkina_Nadia_DS.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Разогрев

## Задание 1

Иногда, когда нужно создавать много однотипных лямбда функций, еще удобнее будет создать функцию, которая будет их генерировать.

Реализуйте функцию ``mod_checker(x, mod=0)``, которая будет **возвращать лямбда функцию** от одного аргумента ``y``, которая будет возвращать ``True``, если остаток от деления ``y`` на ``x`` равен ``mod``, и ``False`` иначе.

Если в ``return`` вашей функции написано выражение, отличное от лямбда функции - задание считается проваленным

**Sample:**

```python
mod_3 = mod_checker(3)

print(mod_3(3)) # True
print(mod_3(4)) # False

mod_3_1 = mod_checker(3, 1)
print(mod_3_1(4)) # True
```

In [112]:
def mod_checker(x, mod = 0):
  """
  Функция возвращает лямбда функцию от одного аргумента y, 
  которая возвращает True, если остаток от деления y на x равен mod, 
  и False иначе.
  """
  return lambda y: y % x == mod

mod_3 = mod_checker(3)

print(mod_3(3))
print(mod_3(4))

mod_3_1 = mod_checker(3, 1)
print(mod_3_1(4))

True
False
True


# Numpy

In [113]:
import numpy as np

## Задание 2
Напишите функцию, которая принимает один аргумент - ``n``. Функция должна создать нампаевскую матрицу размером ``(n, n)`` и залить ее шахматным узором. Порядок узора не имеет значения, важен общий паттерн.

**Sample:**
```python
chess_maze(8)

[[0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]]
```



In [114]:
def chess_maze(n):
  """
  Функция возвращает нампаевскую матрицу размером (n, n), 
  залитую шахматным узором из 0 и 1.
  """
  zeros = np.zeros((n, n), dtype = np.int32)
  zeros[1::2,::2] = 1
  zeros[::2,1::2] = 1
  return zeros.tolist()

chess_maze(8)

[[0, 1, 0, 1, 0, 1, 0, 1],
 [1, 0, 1, 0, 1, 0, 1, 0],
 [0, 1, 0, 1, 0, 1, 0, 1],
 [1, 0, 1, 0, 1, 0, 1, 0],
 [0, 1, 0, 1, 0, 1, 0, 1],
 [1, 0, 1, 0, 1, 0, 1, 0],
 [0, 1, 0, 1, 0, 1, 0, 1],
 [1, 0, 1, 0, 1, 0, 1, 0]]

## Задание 3
Напишите функцию, которая принимает 2 аргумента ``arr`` и ``exclude_values``. ``arr`` - это одномерный нампаевский массив, в котором необходимо поменять знак всем числам (инвертировать), которые есть в массиве ``exclude_values``. Действия необходимо делать прямо в исходном массиве, не создавая копий.

**Sample:**
```python
#Исходный вектор 
arr = np.arange(10+1)
exclude_values = np.arange(4, 8)
 
my_func(arr, exclude_values)
array([ 0  1  2  3 -4 -5 -6 -7  8  9 10])
```

In [115]:
def negative(arr, exclude_values):
  """
  Функция инвертирует в массиве arr значения, заданные в массиве exclude_values.
  """
  arr[np.isin(arr, exclude_values)] *= -1
  return arr

arr = np.arange(10+1)
exclude_values = np.arange(4, 8)
negative(arr, exclude_values)

array([ 0,  1,  2,  3, -4, -5, -6, -7,  8,  9, 10])

## Задание 4
Напишите функцию, которая принимает одномерный положительный нампаевский массив и минимум 4 раза выводит на экран (функция ``print``) этот же массив, в котором у элементов оставлена только целая часть. Все >= 4 раза функция должна использовать разные методы для извлечения целой части.

**Sample:**
```python
#Исходный вектор 
arr = np.random.uniform(low=10, high=100,size=20)
#Исходный вектор arr:
arr
[99.54707368 49.26237526 80.50565073 10.10998238 16.39378916 60.64633657
 25.49637622 31.06574268 94.48636127 73.41204506 75.70638137 70.43830146
 72.28607422 40.59319738 57.85802554 35.39428061 55.25707514 48.00020145
 38.39449991 26.19085017]
 
my_func(arr)

[99. 49. 80. 10. 16. 60. 25. 31. 94. 73. 75. 70. 72. 40. 57. 35. 55. 48.
 38. 26.]
[99. 49. 80. 10. 16. 60. 25. 31. 94. 73. 75. 70. 72. 40. 57. 35. 55. 48.
 38. 26.]
[99. 49. 80. 10. 16. 60. 25. 31. 94. 73. 75. 70. 72. 40. 57. 35. 55. 48.
 38. 26.]
[99 49 80 10 16 60 25 31 94 73 75 70 72 40 57 35 55 48 38 26]
[99. 49. 80. 10. 16. 60. 25. 31. 94. 73. 75. 70. 72. 40. 57. 35. 55. 48.
 38. 26.]
```

В примере 5 выводов print из функции, просто чтобы были :)

In [117]:
def my_func(arr):
  """
  Функция выводит различные способы извлечения целой части.
  """
  print(arr)

  int_arr = arr.astype(np.int32)
  print(int_arr)

  print(np.trunc(arr))

  print(np.floor(arr))

  division = arr // 1
  print(division)
  
  print(np.fix(arr))
  return

arr = np.random.uniform(low = 10, high = 100, size = 20)
my_func(arr)

[73.71885301 58.55943599 28.9845071  83.00914733 96.77575042 28.34625403
 44.55801536 62.73449814 81.31791439 76.77061523 90.41402823 71.58273642
 56.8920995  12.75918121 80.33462773 30.88199841 54.55401629 44.75233262
 22.30151964 61.88425421]
[73 58 28 83 96 28 44 62 81 76 90 71 56 12 80 30 54 44 22 61]
[73. 58. 28. 83. 96. 28. 44. 62. 81. 76. 90. 71. 56. 12. 80. 30. 54. 44.
 22. 61.]
[73. 58. 28. 83. 96. 28. 44. 62. 81. 76. 90. 71. 56. 12. 80. 30. 54. 44.
 22. 61.]
[73. 58. 28. 83. 96. 28. 44. 62. 81. 76. 90. 71. 56. 12. 80. 30. 54. 44.
 22. 61.]
[73. 58. 28. 83. 96. 28. 44. 62. 81. 76. 90. 71. 56. 12. 80. 30. 54. 44.
 22. 61.]


## Задание 5
Напишите функцию, которая принимает два числа - ``N`` и ``p``. ``N`` - это размер стороны квадратной матрицы np.zeros, ``p`` - это количество индексов в матрице (p не превышает N*N), которые нужно заменить на случайные числа. Индексы и числа нужно выбирать случайно. Функция должна возвращать квадратную матрицу со стороной ``N``, в которой ровно ``p`` чисел заменены на случайные.

```python
my_func(N=6, p=4)

[[56.   0.   0.   0.   0.   0.]
 [  0.   0.   0.   0.   0.   0.]
 [99.   0.   0.   0.   0.   0.]
 [  0.   0.   0. 83.   0.   0.]
 [  0.   0.   0.   0.   0.   0.]
 [  0.   0.   0.   0.   1.   0.]]
```

In [116]:
def randomMatrix(N, p):
  """
  Функция возвращает квадратную матрицу размера N, в которой p чисел 
  заменены на рандомные.
  """
  size = N*N
  if (p > size):
    print("P must be less then N*N!")
    return
  arr = np.zeros((N, N), dtype = np.int32)
  indices = np.random.choice(range(size), p, replace = False)
  values = np.random.randint(1, 100, p)
  np.put(arr, indices, values)

  return arr.tolist()

randomMatrix(N = 6, p = 4)

[[0, 0, 0, 0, 0, 0],
 [0, 0, 30, 0, 0, 0],
 [0, 0, 0, 0, 0, 0],
 [0, 33, 0, 86, 0, 0],
 [0, 0, 26, 0, 0, 0],
 [0, 0, 0, 0, 0, 0]]

# Pandas

In [48]:
import pandas as pd

# Задание 6

Любым удобным для вас способом создайте ``dataframe`` c именем ``my_data``, в котором две колонки c именами (``type`` - строки, ``value`` - числа с плавающей точкой) и четыре наблюдения в каждой колонке:

```
type value
B    18.

B    20.

C    10.

C    -10.
```

Какой размер созданного вами датафрейма? (Подумайте, что лучше использовать - информацию из метода df.info() или информацию из метода df.memory_usage()?)
1) Измените тип данных колонки type на category. Как изменился размер датафрейма?
2) Измените тип данных колонки value на менее жадный. Как изменился размер датафрейма?

In [124]:
my_data = pd.DataFrame(
    {
      'type': np.random.choice(['A', 'B', 'C', 'D', 'E', 'F', 'G', 'H', 'I', 'J'], size=4),
      'value': np.random.random_sample(size=4)*100
    }
)
print(my_data)
print(my_data.info())

my_data['type'] = my_data['type'].astype('category')
my_data['value'] = my_data['value'].astype(int)
print(my_data)
print(my_data.info())

# Размер вырос в 1.5 раза

  type      value
0    H  45.057664
1    F  42.928242
2    E   6.665229
3    F  53.328336
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 4 entries, 0 to 3
Data columns (total 2 columns):
 #   Column  Non-Null Count  Dtype  
---  ------  --------------  -----  
 0   type    4 non-null      object 
 1   value   4 non-null      float64
dtypes: float64(1), object(1)
memory usage: 192.0+ bytes
None
  type  value
0    H     45
1    F     42
2    E      6
3    F     53
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 4 entries, 0 to 3
Data columns (total 2 columns):
 #   Column  Non-Null Count  Dtype   
---  ------  --------------  -----   
 0   type    4 non-null      category
 1   value   4 non-null      int64   
dtypes: category(1), int64(1)
memory usage: 296.0 bytes
None


# Задание 7
Любым удобным для вас способом создайте ``dataframe`` c именем ``my_data``, в котором две колонки c именами (``type`` - строки, ``value`` - числа с плавающей точкой) и десять тысяч (10 000) наблюдений в каждой колонке. В колонке ``type`` должно быть 10 уникальных значений.

```python
my_data.shape
____________
(10000, 2)
```

Какой размер созданного вами датафрейма? (Подумайте, что лучше использовать - информацию из метода df.info() или информацию из метода df.memory_usage()?)
1) Измените тип данных колонки type на category. Как изменился размер датафрейма?
2) Измените тип данных колонки value на менее жадный. Как изменился размер датафрейма?

Во сколько раз уменьшился размер исходного датафрейма после выполнения этих двух операций?

In [125]:
my_data = pd.DataFrame(
    {
      'type': np.random.choice(['A', 'B', 'C', 'D', 'E', 'F', 'G', 'H', 'I', 'J'], size = 10000),
      'value': np.random.random_sample(size = 10000)*100
    }
)
print(my_data)
print(my_data.info())

my_data['type'] = my_data['type'].astype('category')
my_data['value'] = my_data['value'].astype(int)
print(my_data)
print(my_data.info())

# Размер уменьшился в 1.76 раз

     type      value
0       F  70.554696
1       H  12.401016
2       G  92.980649
3       C  70.873613
4       G  39.037064
...   ...        ...
9995    A  33.757809
9996    G  21.132881
9997    E  16.450328
9998    C  49.032870
9999    H  91.406004

[10000 rows x 2 columns]
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 10000 entries, 0 to 9999
Data columns (total 2 columns):
 #   Column  Non-Null Count  Dtype  
---  ------  --------------  -----  
 0   type    10000 non-null  object 
 1   value   10000 non-null  float64
dtypes: float64(1), object(1)
memory usage: 156.4+ KB
None
     type  value
0       F     70
1       H     12
2       G     92
3       C     70
4       G     39
...   ...    ...
9995    A     33
9996    G     21
9997    E     16
9998    C     49
9999    H     91

[10000 rows x 2 columns]
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 10000 entries, 0 to 9999
Data columns (total 2 columns):
 #   Column  Non-Null Count  Dtype   
---  ------  --------------  ----

#### Для решения дальнейших задач мы будем использовать следующий датасет, загрузите его с помощью команды:

In [126]:
df = pd.read_csv('https://stepik.org/media/attachments/course/4852/my_stat.csv')

In [ ]:
df

V1    V2 V3   V4
0     2  13.0  B  1.0
1    -1   7.0  B  1.0
2     0  11.0  A  0.0
3     2  11.0  A  2.0
4     0  10.0  B -1.0
..   ..   ... ..  ...
495   1   8.0  A -1.0
496   3   8.0  A  1.0
497  -1  11.0  B  2.0
498   1  11.0  A  2.0
499   0   8.0  B  1.0

[500 rows x 4 columns]

Примечание: все операции с исходным датафреймом должны быть ``inplace``. То есть исходный датафрейм в переменной ``df`` **должен** измениться

# Задание 8

В переменную с именем subset_1 сохраните только первые 19 строк и только 1 и 3 колонку.

В переменную с именем subset_2 сохраните все строки кроме 2, 3 и 18 и только 2 и 4 колонку.

In [127]:
subset_1 = df.head(19).iloc[:, [0, 2]]

subset_2_rows = np.delete(np.arange(df.shape[0]), [1, 2, 17])
subset_2 = df.iloc[subset_2_rows, [1, 3]]

# Задание 9

В переменную subset_3 сохраните только те наблюдения, у которых значения переменной V1 строго больше 0, и значение переменной V3  равняется 'A'.

В переменную  subset_4  сохраните только те наблюдения, у которых значения переменной V2  не равняются 10, или значения переменной V4 больше или равно 1.

In [128]:
subset_3 = df.loc[(df['V1'] > 0) & (df['V3'] == 'A')]
subset_4 = df.loc[(df['V2'] != 10) & (df['V4'] >= 1)]

# Задание 10
Добавьте следующие колонки в df:

1) V5 = V1 + V4
2) V6 = **натуральный** логарифм переменной V2

In [129]:
df = df.assign(V5=lambda x: x['V1'] * x['V4'])
df = df.assign(V6=lambda x: np.log(x['V2']))

# Задание 11

Переименуйте колонки в df.

1) V1 -> session_value

2) V2 -> group

3) V3 -> time

4) V4 -> n_users

In [130]:
renaming = {
  'V1': 'session_value', 
  'V2': 'group',
  'V3': 'time',
  'V4': 'n_users'
}
df.rename(columns = renaming, inplace = True)

# Задание 12
В датафрейме ``my_stat`` в колонке ``session_value`` замените все пропущенные значения на нули.

В колонке ``n_users`` замените все отрицательные значения на медианное значение переменной ``n_users`` (без учета отрицательных значений, разумеется).

In [131]:
my_stat = pd.read_csv('https://stepik.org/media/attachments/course/4852/my_stat_1.csv')

In [110]:
my_stat

session_value  time group  n_users
0            0.0    12     B        9
1            NaN    11     A       -1
2            1.0     8     A        1
3            2.0     9     B        3
4            2.0    10     B        9
5            3.0     8     A        8
6            NaN    11     B        5
7            0.0     9     A        4
8            0.0     8     B      -11
9            0.0     9     A      -20

In [132]:
my_stat['session_value'] = my_stat['session_value'].fillna(0)

n_users_mean = int(my_stat['n_users'].loc[my_stat['n_users'] >= 0].mean())
my_stat.loc[my_stat['n_users'] < 0, 'n_users'] = n_users_mean
my_stat

session_value  time group  n_users
0            0.0    12     B        9
1            0.0    11     A        5
2            1.0     8     A        1
3            2.0     9     B        3
4            2.0    10     B        9
5            3.0     8     A        8
6            0.0    11     B        5
7            0.0     9     A        4
8            0.0     8     B        5
9            0.0     9     A        5